# Generated by Django 4.2.19 on 2025-02-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_alter_paypalpayment_payment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paypalpayment",
            name="currency",
            field=models.CharField(
                choices=[
                    ("usd", "USD"),
                    ("eur", "EUR"),
                    ("jpy", "JPY"),
                    ("gbp", "GBP"),
                    ("chf", "CHF"),
                    ("krw", "KRW"),
                ],
                default="USD",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="stripepayment",
            name="currency",
            field=models.CharField(
                choices=[
                    ("usd", "USD"),
                    ("eur", "EUR"),
                    ("jpy", "JPY"),
                    ("gbp", "GBP"),
                    ("chf", "CHF"),
                    ("krw", "KRW"),
                ],
                default="USD",
                max_length=10,
            ),
        ),
    ]
