# Generated by Django 4.2.19 on 2025-02-24 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplane",
            name="airplane_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="airplane_type",
                to="station.airplanetype",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flight_tickets",
                to="station.flight",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_tickets",
                to="station.order",
            ),
        ),
    ]
