# Generated by Django 4.2.19 on 2025-02-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0002_alter_airplane_airplane_type_alter_ticket_flight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="status",
            field=models.CharField(
                choices=[
                    ("on_time", "On Time"),
                    ("delayed", "Delayed"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                default="on_time",
                max_length=10,
            ),
        ),
    ]
