# Generated by Django 4.2.19 on 2025-02-24 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0003_flight_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="flight",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="station.flight",
            ),
            preserve_default=False,
        ),
    ]
